"""Report generator — produces markdown robustness reports from sweep results."""

import datetime
from pathlib import Path

from trace.metrics.aggregator import SweepResult
from trace.policy_adapter.base import PolicyMetadata


class ReportGenerator:
    """Generates a markdown robustness report from evaluation results."""

    def __init__(self, output_dir: str = "output/reports") -> None:
        self.output_dir = Path(output_dir)

    def generate(
        self,
        policy_meta: PolicyMetadata,
        task_name: str,
        sweep_results: list[SweepResult],
    ) -> str:
        """Generate a markdown report and return its file path."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"report_{policy_meta.name}_{task_name}_{timestamp}.md"
        filepath = self.output_dir / filename

        sections = [
            self._header(policy_meta, task_name),
            self._summary(sweep_results),
        ]

        for result in sweep_results:
            sections.append(self._stressor_section(result))

        sections.append(self._breakpoints(sweep_results))
        sections.append(self._footer())

        content = "\n\n".join(sections)
        filepath.write_text(content)
        return str(filepath)

    def _header(self, meta: PolicyMetadata, task_name: str) -> str:
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        return (
            f"# Trace Robotics — Robustness Report\n\n"
            f"**Policy:** {meta.name}  \n"
            f"**Task:** {task_name}  \n"
            f"**Modalities:** {', '.join(meta.modalities)}  \n"
            f"**Generated:** {now}\n\n"
            f"---"
        )

    def _summary(self, results: list[SweepResult]) -> str:
        lines = ["## Executive Summary\n"]
        for r in results:
            baseline = r.baseline_success_rate()
            degradation = r.max_degradation()
            bp = r.breakpoint_intensity
            bp_str = f"{bp:.2f}" if bp is not None else "none (robust)"

            lines.append(
                f"- **{r.stressor_name}**: baseline {baseline:.0%} success, "
                f"max degradation {degradation:.0%}, "
                f"breakpoint at intensity {bp_str}"
            )

        return "\n".join(lines)

    def _stressor_section(self, result: SweepResult) -> str:
        lines = [f"## {result.stressor_name}\n"]
        lines.append("| Intensity | Success Rate | Catastrophic | Avg Reward | Avg Steps |")
        lines.append("|-----------|-------------|-------------|------------|-----------|")

        for s in result.intensity_stats:
            lines.append(
                f"| {s.intensity:.2f} | {s.success_rate:.0%} | "
                f"{s.catastrophic_failure_rate:.0%} | "
                f"{s.mean_reward:.2f} | {s.mean_steps:.0f} |"
            )

        return "\n".join(lines)

    def _breakpoints(self, results: list[SweepResult]) -> str:
        lines = ["## Breakpoints\n"]
        lines.append("The intensity at which success rate drops below 50%:\n")

        for r in results:
            bp = r.breakpoint_intensity
            if bp is not None:
                lines.append(f"- **{r.stressor_name}**: fails at intensity **{bp:.2f}**")
            else:
                lines.append(f"- **{r.stressor_name}**: no breakpoint detected (robust)")

        return "\n".join(lines)

    def _footer(self) -> str:
        return (
            "---\n\n"
            "*Report generated by Trace Robotics v0.1.0*\n"
            "*https://tracerobotics.com*"
        )
