task:
  name: libero
  max_episode_steps: 300
  success_threshold: 0.95
  params:
    task_suite_name: libero_goal
    task_id: 0
    num_steps_wait: 10
    language_instruction: auto
    render_width: 224
    render_height: 224
